### PR TITLE
🏗 Add @babel/runtime as a dependency

### PR DESCRIPTION
**Pull request by RDIL**
Signed-off-by: Reece Dunham <me@rdil.rocks>

## Summary
* Updates some development dependencies
* Adds `@babel/runtime` as a dependency

## Why
The project currently breaks on Yarn v2 because `@babel/plugin-transform-runtime` calls `@babel/runtime`, which is not explicitly declared as one of the project's dependencies.

## Checklist

- [X] Your code builds clean without any `errors` or `warnings`
- [X] You are using `approved terminology`
- [X] You have added `unit tests`, if apply.

### CODE REVIEW

**Comment by cspotcode** [comment]
Any timeline on when this will be reviewed, merged, and released?  I'm coming from https://github.com/facebook/docusaurus/issues/3003

**Comment by themgoncalves** [comment]
Hi @RDIL, thanks for contribution, but sadly I cannot accept this `pull request` as it contains changes outside of the scope.

For that, I recommend you to only add the `@babel/runtime` into **`devDependencies` ** (not `dependencies` itself) and remove all other changes that you made.

Cheers.

**Comment by themgoncalves** [comment]
@cspotcode per commend above.

**Review by themgoncalves — CHANGES_REQUESTED** [review]
Hi @RDIL, thanks for contribution, but sadly I cannot accept this `pull request` as it contains changes outside of the scope.

For that, I recommend you to only add the `@babel/runtime` into **`devDependencies`** (not `dependencies` itself) and remove all other changes that you made.

Cheers.

**Comment by themgoncalves** [comment]
@cspotcode per commend above.

**Comment by RDIL** [comment]
@themgoncalves I can revert the other changes, **but this does need** to be in normal dependencies, because it imports from the `@babel/runtime` at runtime.

**Comment by ylemkimon** [comment]
From [`@babel/plugin-transform-runtime` docs](https://babeljs.io/docs/en/babel-plugin-transform-runtime#technical-details):
> Make sure you include `@babel/runtime` as a dependency.

**Review by themgoncalves — APPROVED** [review]
LGTM

**Comment by themgoncalves** [comment]
@RDIL, @ylemkimon you can find this `merge` in the **just released `v0.3.0`**.

**Pull request merged**
